### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by VB10** [Woman-Coders/e-Odevim#1]
elinize sağlık

- daha fazla klasör yapıp projenizi düzelnemsiniz misal core ve view viewin altında sizin sayfalarınız gibi
- theme dosyanız olmalı ve tüm değerler ordan gelmeli
- sayfalradki widgetleri parçalamnız ve atomic hale geitmreniz lazım
- syaflarınza vm viewcontorler gibi bir sınf daha yaparak iş yüklerini oradan lamasınız
- sayfalardaki elle verilmiş değerleri const sınfalrından singleton gibi patternler ile yönetmeilsiniz

**Comment by HaNuNa42** [comment]
@VB10  teşekkür ederiz hocam önerileriniz için  :) github kullanmayı yeni yeni öğrendiğimden dolayı ancak kapatabildim bu issue.yu :)
